// TODO: API 연동 후 제거
import type { LetterItem } from "../shared/schemas/letterSchema";

export const MOCK_SENT: LetterItem[] = [
  // 1-20: 생일 및 감사 (Theme 1)
  { id: "1", to: "소중한 친구", from: "마음을 담아", preview: "진심으로 생일 감사해!...", content: "오늘 너의 생일을 진심으로 감사해. 벌써 이렇게 또 한 해가 지나갔다는 게 신기하기도 하고, 그만큼 우리가 함께한 시간이 쌓였다는 게 새삼 감사하게 느껴져.", keyword: "생일", theme: 1, createdAt: "04월 22일" },
  { id: "2", to: "감사하는 언니", from: "동생이", preview: "언니 생일 감사해요!...", content: "언니 생일 정말 감사해! 항상 나 잘 챙겨줘서 고마워. 올해는 언니한테 좋은 일만 가득하길 바랄게.", keyword: "생일", theme: 1, createdAt: "04월 20일" },
  { id: "3", to: "팀장님", from: "팀원 일동", preview: "생일 감사드립니다!...", content: "팀장님 생신 감사드립니다! 항상 저희 이끌어주셔서 감사합니다. 건강하세요!", keyword: "생일", theme: 1, createdAt: "04월 18일" },
  { id: "4", to: "베프", from: "단짝", preview: "야 생일 감사한다!!...", content: "야 생일 감사한다!! 케이크 먹으러 가자. 오늘 완전 네 날이다!", keyword: "생일", theme: 1, createdAt: "04월 17일" },
  { id: "5", to: "엄마", from: "아들", preview: "엄마 생신 감사해요...", content: "엄마 생신 진심으로 감사드려요. 항상 감사합니다. 맛있는 거 드세요!", keyword: "생일", theme: 1, createdAt: "04월 15일" },
  { id: "6", to: "아빠", from: "딸", preview: "아빠 생신 감사해요...", content: "감사하는 우리 아빠, 생신 감사드려요! 늘 든든한 버팀목이 되어주셔서 감사합니다.", keyword: "생일", theme: 1, createdAt: "04월 12일" },
  { id: "7", to: "남친", from: "여친", preview: "자기야 생일 감사해...", content: "자기야 생일 정말 감사해! 우리가 함께하는 두 번째 생일이네. 감사해!", keyword: "생일", theme: 1, createdAt: "04월 10일" },
  { id: "8", to: "여친", from: "남친", preview: "공주님 생일 감사해...", content: "세상에서 제일 예쁜 우리 공주님 생일 감사해! 오늘 데이트 즐겁게 하자.", keyword: "생일", theme: 1, createdAt: "04월 08일" },
  { id: "9", to: "동료", from: "같은 팀", preview: "생일 감사해!", content: "생일 감사해! 오늘 점심은 맛있는 거 먹자!", keyword: "생일", theme: 1, createdAt: "04월 05일" },
  { id: "10", to: "선배", from: "후배", preview: "생일 감사드려요...", content: "선배님 생일 감사드려요! 항상 많이 배우고 있습니다.", keyword: "생일", theme: 1, createdAt: "04월 02일" },
  { id: "11", to: "친구", from: "그리움", preview: "생일인데 잘 지내니...", content: "생일인데 잘 지내니? 오랜만에 연락해서 미안해. 생일 감사한다!", keyword: "생일", theme: 1, createdAt: "03월 30일" },
  { id: "12", to: "동생", from: "형", preview: "생일 감사한다 녀석아...", content: "생일 감사한다 녀석아! 용돈 보냈다 맛있는 거 사 먹어라.", keyword: "생일", theme: 1, createdAt: "03월 28일" },
  { id: "13", to: "친구", from: "옛 친구", preview: "벌써 생일이네...", content: "벌써 생일이네. 많이 감사한다! 항상 행복하길 바라.", keyword: "생일", theme: 1, createdAt: "03월 25일" },
  { id: "14", to: "지인", from: "응원", preview: "생일 진심으로 감사드려요...", content: "생일 진심으로 감사드려요! 하시는 일 다 잘 되시길 응원합니다.", keyword: "생일", theme: 1, createdAt: "03월 20일" },
  { id: "15", to: "조카", from: "이모", preview: "우리 조카 생일 감사해...", content: "우리 조카 생일 감사해! 쑥쑥 크느라 고생 많았어.", keyword: "생일", theme: 1, createdAt: "03월 15일" },
  { id: "16", to: "친구", from: "베프", preview: "생일 감사한다!!...", content: "생일 감사한다!! 올해는 대박 터지자!", keyword: "생일", theme: 1, createdAt: "03월 10일" },
  { id: "17", to: "동료", from: "동기", preview: "생일 감사해...", content: "생일 감사해! 야근하지 말고 오늘은 얼른 들어가라.", keyword: "생일", theme: 1, createdAt: "03월 05일" },
  { id: "18", to: "누나", from: "동생", preview: "누나 생일 감사해...", content: "누나 생일 감사해! 나중에 밥 한 끼 하자.", keyword: "생일", theme: 1, createdAt: "03월 01일" },
  { id: "19", to: "친구", from: "소중한 친구", preview: "생일 감사해...", content: "생일 감사해! 변치 말고 오래오래 보자.", keyword: "생일", theme: 1, createdAt: "02월 25일" },
  { id: "20", to: "선배", from: "후배", preview: "생신 감사드려요...", content: "선배님 생신 감사드려요! 건강하세요.", keyword: "생일", theme: 1, createdAt: "02월 20일" },

  // 21-40: 감사와 표현 (Theme 2)
  { id: "21", to: "엄마", from: "마음을 담아", preview: "항상 저를 위해 애써주셔서...", content: "항상 저를 위해 애써주셔서 감사드려요. 엄마 덕분에 제가 이렇게 잘 자랄 수 있었어요.", keyword: "감사", theme: 2, createdAt: "04월 15일" },
  { id: "22", to: "선생님", from: "제자", preview: "선생님 감사합니다...", content: "선생님, 늘 가르침 주셔서 감사합니다. 존경합니다.", keyword: "감사", theme: 2, createdAt: "04월 10일" },
  { id: "23", to: "도와주신 분", from: "고마운 마음", preview: "정말 감사합니다...", content: "그때 도와주신 덕분에 정말 큰 힘이 됐어요. 감사합니다.", keyword: "감사", theme: 2, createdAt: "04월 05일" },
  { id: "24", to: "동료", from: "같은 팀", preview: "도와줘서 고마워...", content: "어제 야근할 때 도와줘서 정말 고마워. 덕분에 빨리 끝났어.", keyword: "감사", theme: 2, createdAt: "04월 01일" },
  { id: "25", to: "친구", from: "베프", preview: "항상 고마워...", content: "내 이야기 다 들어줘서 고마워. 너밖에 없다 진짜.", keyword: "감사", theme: 2, createdAt: "03월 28일" },
  { id: "26", to: "아빠", from: "딸", preview: "아빠 항상 감사합니다...", content: "아빠, 늘 우리 가족 위해 일하시느라 고생 많으세요. 감사합니다.", keyword: "감사", theme: 2, createdAt: "03월 25일" },
  { id: "27", to: "지인", from: "선물", preview: "선물 감사합니다...", content: "보내주신 선물 정말 감사합니다. 잘 쓰겠습니다.", keyword: "감사", theme: 2, createdAt: "03월 20일" },
  { id: "28", to: "교수님", from: "학생", preview: "지도 감사드립니다...", content: "교수님, 이번 학기 지도 감사드립니다. 많이 배웠습니다.", keyword: "감사", theme: 2, createdAt: "03월 15일" },
  { id: "29", to: "선배", from: "후배", preview: "밥 잘 먹었습니다...", content: "어제 밥 사주셔서 감사합니다! 정말 맛있었어요.", keyword: "감사", theme: 2, createdAt: "03월 10일" },
  { id: "30", to: "친구", from: "고마움", preview: "생각해줘서 고마워...", content: "내 걱정해줘서 고마워. 너 덕분에 힘이 나.", keyword: "감사", theme: 2, createdAt: "03월 05일" },
  { id: "31", to: "엄마", from: "아들", preview: "낳아주셔서 감사합니다...", content: "엄마, 저 낳아주시고 길러주셔서 감사합니다. 효도할게요.", keyword: "감사", theme: 2, createdAt: "02월 28일" },
  { id: "32", to: "가족", from: "감사", preview: "함께해서 감사해...", content: "우리 가족 함께해서 감사해. 감사합니다.", keyword: "감사", theme: 2, createdAt: "02월 20일" },
  { id: "33", to: "팀장님", from: "팀원", preview: "이끌어주셔서 감사합니다...", content: "팀장님, 부족한 저 이끌어주셔서 감사합니다.", keyword: "감사", theme: 2, createdAt: "02월 15일" },
  { id: "34", to: "친구", from: "고마워", preview: "함께해주어 고마워...", content: "힘든 시절 함께해주어 고마워. 잊지 않을게.", keyword: "감사", theme: 2, createdAt: "02월 10일" },
  { id: "35", to: "동료", from: "협업", preview: "프로젝트 감사했습니다...", content: "이번 프로젝트 같이해서 감사했습니다. 수고하셨어요.", keyword: "감사", theme: 2, createdAt: "02월 05일" },
  { id: "36", to: "누구에게나", from: "마음", preview: "늘 감사합니다...", content: "그냥 문득 감사한 마음이 들어서 연락해요. 늘 고맙습니다.", keyword: "감사", theme: 2, createdAt: "01월 30일" },
  { id: "37", to: "친구", from: "우정", preview: "내 곁에 있어줘서...", content: "내 곁에 있어줘서 감사해. 앞으로도 잘 부탁해.", keyword: "감사", theme: 2, createdAt: "01월 25일" },
  { id: "38", to: "지인", from: "응원", preview: "도움 감사드립니다...", content: "도움 주셔서 감사드립니다. 큰 도움이 되었습니다.", keyword: "감사", theme: 2, createdAt: "01월 20일" },
  { id: "39", to: "선배", from: "후배", preview: "조언 감사합니다...", content: "해주신 조언 감사합니다. 열심히 하겠습니다.", keyword: "감사", theme: 2, createdAt: "01월 15일" },
  { id: "40", to: "연인", from: "감사", preview: "만나줘서 고마워...", content: "나랑 만나줘서 고마워. 너랑 있으면 정말 행복해.", keyword: "감사", theme: 2, createdAt: "01월 10일" },

  // 41-60: 응원과 위로 (Theme 3)
  { id: "41", to: "친구", from: "응원", preview: "힘내, 넌 할 수 있어...", content: "힘내, 넌 할 수 있어! 지금 힘들어도 곧 좋은 날이 올 거야.", keyword: "응원", theme: 3, createdAt: "04월 20일" },
  { id: "42", to: "수험생", from: "응원", preview: "합격 기원해...", content: "합격 기원해! 마지막까지 페이스 잃지 말고 파이팅!", keyword: "응원", theme: 3, createdAt: "04월 18일" },
  { id: "43", to: "동료", from: "격려", preview: "오늘도 고생 많았어...", content: "오늘도 고생 많았어! 맛있는 거 먹고 푹 쉬어.", keyword: "응원", theme: 3, createdAt: "04월 15일" },
  { id: "44", to: "친구", from: "위로", preview: "울지 마...", content: "울지 마... 다 지나갈 거야. 내가 옆에 있을게.", keyword: "응원", theme: 3, createdAt: "04월 10일" },
  { id: "45", to: "지인", from: "희망", preview: "새로운 시작을 응원해...", content: "새로운 시작을 응원해! 분명 잘 해낼 거야.", keyword: "응원", theme: 3, createdAt: "04월 05일" },
  { id: "46", to: "동생", from: "형/누나", preview: "너는 최고야...", content: "너는 최고야! 기죽지 말고 네 꿈을 펼쳐봐.", keyword: "응원", theme: 3, createdAt: "04월 01일" },
  { id: "47", to: "취준생", from: "응원", preview: "조금만 더 힘내자...", content: "조금만 더 힘내자! 곧 좋은 소식 있을 거야.", keyword: "응원", theme: 3, createdAt: "03월 28일" },
  { id: "48", to: "친구", from: "믿음", preview: "난 너 믿어...", content: "난 너 믿어! 너라면 충분히 해낼 수 있어.", keyword: "응원", theme: 3, createdAt: "03월 25일" },
  { id: "49", to: "연인", from: "격려", preview: "많이 힘들지?...", content: "많이 힘들지? 내가 다독여줄게. 고생했어.", keyword: "응원", theme: 3, createdAt: "03월 20일" },
  { id: "50", to: "친구", from: "응원", preview: "주말엔 푹 쉬어...", content: "이번 주도 고생했어. 주말엔 아무 생각 말고 푹 쉬어.", keyword: "응원", theme: 3, createdAt: "03월 15일" },
  { id: "51", to: "지인", from: "응원", preview: "건강 잘 챙기고...", content: "건강 잘 챙기고! 아프지 말고 힘내자.", keyword: "응원", theme: 3, createdAt: "03월 10일" },
  { id: "52", to: "동료", from: "파이팅", preview: "오늘 프로젝트 파이팅!...", content: "오늘 프로젝트 파이팅! 우리 잘해보자.", keyword: "응원", theme: 3, createdAt: "03월 05일" },
  { id: "53", to: "친구", from: "위로", preview: "기운 내...", content: "기운 내! 맛있는 거 사줄게.", keyword: "응원", theme: 3, createdAt: "03월 01일" },
  { id: "54", to: "엄마", from: "아들", preview: "건강하세요...", content: "엄마, 아프지 말고 항상 건강하세요. 감사해요.", keyword: "응원", theme: 3, createdAt: "02월 25일" },
  { id: "55", to: "친구", from: "용기", preview: "용기 내서 도전해봐...", content: "용기 내서 도전해봐! 결과가 어떻든 경험이 될 거야.", keyword: "응원", theme: 3, createdAt: "02월 20일" },
  { id: "56", to: "동생", from: "언니/오빠", preview: "공부하느라 고생해...", content: "공부하느라 고생해! 간식 보냈다.", keyword: "응원", theme: 3, createdAt: "02월 15일" },
  { id: "57", to: "친구", from: "응원", preview: "늘 응원할게...", content: "너의 앞날을 늘 응원할게. 힘내!", keyword: "응원", theme: 3, createdAt: "02월 10일" },
  { id: "58", to: "지인", from: "격려", preview: "잘하고 있어...", content: "지금까지 잘해왔어. 조금만 더 힘내자!", keyword: "응원", theme: 3, createdAt: "02월 05일" },
  { id: "59", to: "친구", from: "위로", preview: "너무 걱정 마...", content: "너무 걱정 마. 다 잘 될 거야.", keyword: "응원", theme: 3, createdAt: "01월 30일" },
  { id: "60", to: "나 자신", from: "나", preview: "오늘도 고생했어...", content: "오늘도 고생했어! 내일은 더 행복하자.", keyword: "응원", theme: 3, createdAt: "01월 25일" },

  // 61-70: 감사 (Theme 4)
  { id: "61", to: "친구", from: "감사", preview: "날씨 좋다...", content: "날씨 좋다! 산책하러 안 나갈래?", keyword: "감사", theme: 4, createdAt: "04월 20일" },
  { id: "62", to: "동료", from: "감사", preview: "점심 뭐 먹을까?...", content: "점심 뭐 먹을까? 맛집 찾아놨어.", keyword: "감사", theme: 4, createdAt: "04월 18일" },
  { id: "63", to: "친구", from: "감사", preview: "커피 한잔하자...", content: "커피 한잔하자! 카페에서 수다 떨고 싶어.", keyword: "감사", theme: 4, createdAt: "04월 15일" },
  { id: "64", to: "가족", from: "감사", preview: "저녁에 뭐 먹어?...", content: "저녁에 뭐 먹어? 메뉴 추천 좀!", keyword: "감사", theme: 4, createdAt: "04월 10일" },
  { id: "65", to: "친구", from: "감사", preview: "영화 보러 가자...", content: "요즘 재밌는 영화 많던데 보러 가자.", keyword: "감사", theme: 4, createdAt: "04월 05일" },
  { id: "66", to: "연인", from: "감사", preview: "보고 싶어...", content: "보고 싶어! 주말에 뭐 할까?", keyword: "감사", theme: 4, createdAt: "04월 01일" },
  { id: "67", to: "친구", from: "감사", preview: "잘 지내지?...", content: "잘 지내지? 갑자기 생각나서 연락했어.", keyword: "감사", theme: 4, createdAt: "03월 28일" },
  { id: "68", to: "지인", from: "감사", preview: "좋은 하루 보내!...", content: "오늘 하루도 즐겁게 보내!", keyword: "감사", theme: 4, createdAt: "03월 25일" },
  { id: "69", to: "친구", from: "감사", preview: "사진 봤어...", content: "SNS에 올린 사진 봤어! 진짜 예쁘더라.", keyword: "감사", theme: 4, createdAt: "03월 20일" },
  { id: "70", to: "동료", from: "감사", preview: "퇴근하자!...", content: "오늘 금요일이다! 퇴근하고 맥주 한잔할까?", keyword: "감사", theme: 4, createdAt: "03월 15일" },

  // 71-80: 감사 (Theme 5)
  { id: "71", to: "연인", from: "감사", preview: "감사해...", content: "감사해! 너랑 함께라서 매일이 행복해.", keyword: "감사", theme: 4, createdAt: "04월 20일" },
  { id: "72", to: "남편", from: "아내", preview: "여보 감사해요...", content: "여보 오늘 하루도 고생 많았어요. 감사해요.", keyword: "감사", theme: 4, createdAt: "04월 18일" },
  { id: "73", to: "아내", from: "남편", preview: "고마워요...", content: "항상 내 옆에 있어 줘서 고마워요. 감사합니다.", keyword: "감사", theme: 4, createdAt: "04월 15일" },
  { id: "74", to: "연인", from: "감사", preview: "우리 오래가자...", content: "우리 오래가자! 감사해.", keyword: "감사", theme: 4, createdAt: "04월 10일" },
  { id: "75", to: "연인", from: "감사", preview: "네가 최고야...", content: "네가 최고야! 세상에서 제일 감사해.", keyword: "감사", theme: 4, createdAt: "04월 05일" },
  { id: "76", to: "연인", from: "감사", preview: "보고 싶어...", content: "자꾸 네 생각이 나. 진짜 감사하나 봐.", keyword: "감사", theme: 4, createdAt: "04월 01일" },
  { id: "77", to: "연인", from: "감사", preview: "좋은 꿈 꿔...", content: "좋은 꿈 꿔! 꿈에서 만나. 감사해.", keyword: "감사", theme: 4, createdAt: "03월 28일" },
  { id: "78", to: "연인", from: "감사", preview: "행복해...", content: "너랑 있어서 정말 행복해. 감사해!", keyword: "감사", theme: 4, createdAt: "03월 25일" },
  { id: "79", to: "연인", from: "감사", preview: "함께해줘서 고마워...", content: "나랑 함께해줘서 고마워. 영원히 감사해.", keyword: "감사", theme: 4, createdAt: "03월 20일" },
  { id: "80", to: "연인", from: "감사", preview: "감사한다...", content: "무슨 말이 필요해. 감사한다.", keyword: "감사", theme: 4, createdAt: "03월 15일" },
];