import type { LetterItem } from "../shared/schemas/letterSchema";

export const MOCK_RECEIVED: LetterItem[] = [
  {
    id: "r1",
    to: "소중한 당신에게",
    from: "친구",
    preview: "진심으로 생일 축하해!",
    content:
      "진심으로 생일 축하해!\n\n우리가 함께한 시간들이 나에게는 큰 선물이야. 항상 곁에 있어줘서 고마워!",
    keyword: "생일",
    theme: 1,
    createdAt: "04월 22일",
  },
  {
    id: "r2",
    to: "선생님에게",
    from: "제자가",
    preview: "안녕하세요 선생님 스승의날로 편지를 보내네요",
    content:
      "안녕하세요 선생님 스승의날로 편지를 보내네요\n\n덕분에 정신차리고 삶을 살아가고 있어요. 감사의 말씀을 전하고 싶어서 편지를 보내요",
    keyword: "감사",
    theme: 3,
    createdAt: "04월 12일",
  },
  {
    id: "r3",
    to: "엄마에게",
    from: "아들이",
    preview: "엄마 생신 축하드려요!",
    content:
      "엄마 생신 축하드려요!\n\n항상 받기만 해서 죄송해요. 이제는 제가 더 잘할게요. 사랑합니다.",
    keyword: "생일",
    theme: 2,
    createdAt: "04월 05일",
  },
  {
    id: "r4",
    to: "동료에게",
    from: "팀원이",
    preview: "프로젝트 고생 많으셨습니다",
    content:
      "프로젝트 고생 많으셨습니다.\n\n이번 프로젝트 덕분에 많이 배웠습니다. 나중에 꼭 같이 일해요!",
    keyword: "감사",
    theme: 4,
    createdAt: "04월 15일",
  },
  {
    id: "r5",
    to: "친구에게",
    from: "베프가",
    preview: "요즘 왜 연락이 없어?",
    content:
      "요즘 왜 연락이 없어?\n\n바쁜 건 알지만 너무하다! 시간 나면 맛있는 거 먹으러 가자.",
    keyword: "생일",
    theme: 1,
    createdAt: "04월 08일",
  },
  {
    id: "r6",
    to: "짝꿍에게",
    from: "마음이",
    preview: "좋아하는 마음을 전하고 싶어",
    content:
      "좋아하는 마음을 전하고 싶어.\n\n사실 너를 볼 때마다 가슴이 두근거려. 이번 주말에 시간 어때?",
    keyword: "감사",
    theme: 2,
    createdAt: "04월 20일",
  },
  {
    id: "r7",
    to: "후배에게",
    from: "선배가",
    preview: "시험은 잘 봤니?",
    content:
      "시험은 잘 봤니?\n\n고생한 거 다 아니까 너무 걱정 마. 너는 충분히 잘하고 있어.",
    keyword: "생일",
    theme: 3,
    createdAt: "04월 18일",
  },
  {
    id: "r8",
    to: "아빠에게",
    from: "딸이",
    preview: "아빠 건강 챙기세요",
    content:
      "아빠 건강 챙기세요.\n\n요즘 날씨가 변덕스러운데 감기 조심하시고 밥 잘 챙겨 드세요!",
    keyword: "감사",
    theme: 4,
    createdAt: "04월 02일",
  },
  {
    id: "r9",
    to: "친구에게",
    from: "언제나",
    preview: "주말에 시간 비워놔!",
    content:
      "주말에 시간 비워놔!\n\n우리 여행 가기로 한 거 잊지 않았지? 기대된다!",
    keyword: "생일",
    theme: 1,
    createdAt: "04월 25일",
  },
  {
    id: "r10",
    to: "지인에게",
    from: "고마운이",
    preview: "도와주셔서 감사합니다",
    content:
      "도와주셔서 감사합니다.\n\n혼자 고민하던 문제였는데 덕분에 잘 해결했어요. 다음에 밥 한 끼 대접할게요!",
    keyword: "감사",
    theme: 3,
    createdAt: "04월 11일",
  },
  {
    id: "r11",
    to: "소중한 당신에게",
    from: "친구",
    preview: "비 오는 날 생각나서",
    content:
      "비 오는 날 생각나서 연락했어.\n\n따뜻한 차 한잔 마시면서 마음 잘 추스르길 바랄게.",
    keyword: "생일",
    theme: 2,
    createdAt: "04월 09일",
  },
  {
    id: "r12",
    to: "선배님에게",
    from: "후배가",
    preview: "취업 축하드립니다!",
    content:
      "취업 축하드립니다!\n\n선배님 노력을 옆에서 다 지켜봤기에 더 기뻐요. 정말 고생 많으셨습니다.",
    keyword: "감사",
    theme: 1,
    createdAt: "04월 28일",
  },
  {
    id: "r13",
    to: "나에게",
    from: "미래의내가",
    preview: "힘든 하루였지?",
    content:
      "힘든 하루였지?\n\n오늘도 버티느라 고생 많았어. 내일은 더 좋은 일이 생길 거야.",
    keyword: "생일",
    theme: 4,
    createdAt: "04월 01일",
  },
  {
    id: "r14",
    to: "동생에게",
    from: "언니가",
    preview: "공부하느라 힘들지?",
    content:
      "공부하느라 힘들지?\n\n너무 무리하지 마. 잠시 쉬어가는 것도 실력이래.",
    keyword: "감사",
    theme: 3,
    createdAt: "04월 14일",
  },
  {
    id: "r15",
    to: "친구에게",
    from: "단짝",
    preview: "우리 벌써 10년이네",
    content:
      "우리 벌써 10년이네.\n\n어릴 때부터 지금까지 옆에 있어 줘서 고마워. 앞으로도 잘 부탁해.",
    keyword: "생일",
    theme: 2,
    createdAt: "04월 19일",
  },
  {
    id: "r16",
    to: "선생님에게",
    from: "제자가",
    preview: "항상 감사합니다",
    content:
      "항상 감사합니다.\n\n선생님 덕분에 꿈을 찾을 수 있었어요. 건강하세요!",
    keyword: "감사",
    theme: 4,
    createdAt: "04월 07일",
  },
  {
    id: "r17",
    to: "연인에게",
    from: "자기야",
    preview: "보고 싶어서 보내는 편지",
    content:
      "보고 싶어서 보내는 편지.\n\n하루 종일 네 생각뿐이야. 우리 오늘 밤에 만날까?",
    keyword: "생일",
    theme: 1,
    createdAt: "04월 24일",
  },
  {
    id: "r18",
    to: "동료에게",
    from: "파트너",
    preview: "회의 자료 고마워",
    content:
      "회의 자료 고마워.\n\n덕분에 발표 무사히 마쳤어. 저녁에 시원한 거 먹으러 가자!",
    keyword: "감사",
    theme: 3,
    createdAt: "04월 13일",
  },
  {
    id: "r19",
    to: "친구에게",
    from: "멀리사는",
    preview: "거기는 날씨 어때?",
    content:
      "거기는 날씨 어때?\n\n여긴 벌써 꽃이 많이 폈어. 너도 곧 보러 오면 좋겠다.",
    keyword: "생일",
    theme: 2,
    createdAt: "04월 03일",
  },
  {
    id: "r20",
    to: "부모님께",
    from: "아들이",
    preview: "죄송하고 고마워요",
    content:
      "죄송하고 고마워요.\n\n표현은 잘 안 하지만 항상 존경하고 있어요. 건강만 하세요.",
    keyword: "감사",
    theme: 4,
    createdAt: "04월 26일",
  },
  {
    id: "r21",
    to: "친구에게",
    from: "너의벗",
    preview: "오늘 기분은 어때?",
    content: "오늘 기분은 어때?\n\n힘든 일 있으면 말해. 내가 다 들어줄게.",
    keyword: "생일",
    theme: 1,
    createdAt: "04월 17일",
  },
  {
    id: "r22",
    to: "멘토님에게",
    from: "멘티가",
    preview: "조언 감사합니다",
    content:
      "조언 감사합니다.\n\n고민하던 부분이 덕분에 명확해졌어요. 열심히 해보겠습니다!",
    keyword: "감사",
    theme: 2,
    createdAt: "04월 29일",
  },
  {
    id: "r23",
    to: "친구에게",
    from: "동기",
    preview: "이번 시험 파이팅!",
    content:
      "이번 시험 파이팅!\n\n우리 이번엔 꼭 장학금 받자. 도서관에서 보자.",
    keyword: "생일",
    theme: 3,
    createdAt: "04월 06일",
  },
  {
    id: "r24",
    to: "소중한 당신에게",
    from: "나",
    preview: "오늘 하루 수고했어",
    content:
      "오늘 하루 수고했어.\n\n실수 좀 했으면 어때. 내일 다시 잘하면 되지!",
    keyword: "감사",
    theme: 4,
    createdAt: "04월 10일",
  },
  {
    id: "r25",
    to: "가족에게",
    from: "딸이",
    preview: "주말에 갈게",
    content: "주말에 갈게.\n\n엄마가 해주는 김치찌개가 너무 먹고 싶어.",
    keyword: "생일",
    theme: 1,
    createdAt: "04월 30일",
  },
  {
    id: "r26",
    to: "친구에게",
    from: "옛동료",
    preview: "잘 지내지?",
    content:
      "잘 지내지?\n\n그때 우리 같이 프로젝트 했던 기억이 난다. 다들 보고 싶네.",
    keyword: "감사",
    theme: 3,
    createdAt: "04월 14일",
  },
  {
    id: "r27",
    to: "연인에게",
    from: "사랑꾼",
    preview: "100일 축하해",
    content: "100일 축하해.\n\n우리 앞으로 1000일, 10000일 더 행복하게 지내자.",
    keyword: "생일",
    theme: 2,
    createdAt: "04월 21일",
  },
  {
    id: "r28",
    to: "친구에게",
    from: "너의친구",
    preview: "생일 선물 기대해!",
    content:
      "생일 선물 기대해!\n\n네가 제일 좋아하는 걸로 준비했어. 주말에 만나!",
    keyword: "감사",
    theme: 4,
    createdAt: "04월 23일",
  },
  {
    id: "r29",
    to: "선배님에게",
    from: "후배",
    preview: "밥 잘 먹었습니다",
    content:
      "밥 잘 먹었습니다.\n\n너무 얻어먹기만 하는 것 같네요. 다음엔 제가 살게요!",
    keyword: "생일",
    theme: 1,
    createdAt: "04월 04일",
  },
  {
    id: "r30",
    to: "동생에게",
    from: "오빠가",
    preview: "용돈 보냈다",
    content: "용돈 보냈다.\n\n맛있는 거 사 먹고 공부 열심해. 연락 자주 하고!",
    keyword: "감사",
    theme: 3,
    createdAt: "04월 02일",
  },
  {
    id: "r31",
    to: "친구에게",
    from: "베프",
    preview: "너 요즘 얼굴이 안 좋아 보여",
    content:
      "너 요즘 얼굴이 안 좋아 보여.\n\n무리하지 말고 좀 쉬어. 밥은 챙겨 먹고 있지?",
    keyword: "생일",
    theme: 2,
    createdAt: "04월 07일",
  },
  {
    id: "r32",
    to: "부모님께",
    from: "딸",
    preview: "사랑해요",
    content: "사랑해요.\n\n항상 받기만 해서 죄송하고, 꼭 효도할게요.",
    keyword: "감사",
    theme: 4,
    createdAt: "04월 28일",
  },
  {
    id: "r33",
    to: "동료에게",
    from: "팀원",
    preview: "업무 분담 감사합니다",
    content:
      "업무 분담 감사합니다.\n\n덕분에 퇴근 일찍 할 수 있었어요. 내일 봬요!",
    keyword: "생일",
    theme: 1,
    createdAt: "04월 15일",
  },
  {
    id: "r34",
    to: "친구에게",
    from: "단짝",
    preview: "우리 떡볶이 먹으러 가자",
    content:
      "우리 떡볶이 먹으러 가자.\n\n시험 기간이라 너무 스트레스받아. 매운 거 먹고 풀자!",
    keyword: "감사",
    theme: 3,
    createdAt: "04월 19일",
  },
  {
    id: "r35",
    to: "짝꿍에게",
    from: "비밀",
    preview: "너 오늘 예쁘더라",
    content:
      "너 오늘 예쁘더라.\n\n물론 평소에도 예쁘지만, 오늘 유독 눈에 띄었어.",
    keyword: "생일",
    theme: 2,
    createdAt: "04월 05일",
  },
  {
    id: "r36",
    to: "후배에게",
    from: "선배",
    preview: "과제 다 했니?",
    content: "과제 다 했니?\n\n너무 헤매고 있으면 연락해. 도와줄 테니까.",
    keyword: "감사",
    theme: 4,
    createdAt: "04월 08일",
  },
  {
    id: "r37",
    to: "친구에게",
    from: "베프",
    preview: "오늘 뭐해?",
    content: "오늘 뭐해?\n\n심심하면 카페나 가자. 할 얘기가 산더미야.",
    keyword: "생일",
    theme: 1,
    createdAt: "04월 11일",
  },
  {
    id: "r38",
    to: "선배님에게",
    from: "후배",
    preview: "졸업 축하드려요!",
    content:
      "졸업 축하드려요!\n\n사회에서도 멋지게 성공하실 거라 믿어요. 응원합니다!",
    keyword: "감사",
    theme: 3,
    createdAt: "04월 25일",
  },
  {
    id: "r39",
    to: "가족에게",
    from: "엄마",
    preview: "집에 오면 연락해",
    content:
      "집에 오면 연락해.\n\n저녁 차려놓고 기다릴게. 오늘 많이 추우니까 따뜻하게 입고 와.",
    keyword: "생일",
    theme: 2,
    createdAt: "04월 12일",
  },
  {
    id: "r40",
    to: "친구에게",
    from: "단짝",
    preview: "여행 가자!",
    content: "여행 가자!\n\n이번 방학엔 제주도 가고 싶어. 계획은 내가 짤게!",
    keyword: "감사",
    theme: 4,
    createdAt: "04월 20일",
  },
  {
    id: "r41",
    to: "연인에게",
    from: "자기야",
    preview: "오늘 데이트 좋았어",
    content:
      "오늘 데이트 좋았어.\n\n다음엔 내가 가고 싶은 곳으로 가자. 벌써 보고 싶네.",
    keyword: "생일",
    theme: 1,
    createdAt: "04월 03일",
  },
  {
    id: "r42",
    to: "지인에게",
    from: "감사함",
    preview: "선물 감사합니다",
    content:
      "선물 감사합니다.\n\n취향 저격이에요! 너무 예뻐서 매일 쓰고 있어요.",
    keyword: "감사",
    theme: 3,
    createdAt: "04월 16일",
  },
  {
    id: "r43",
    to: "나에게",
    from: "오늘의나",
    preview: "힘내자",
    content: "힘내자.\n\n남들 시선보다는 내 행복이 중요한 거야. 잘하고 있어.",
    keyword: "생일",
    theme: 2,
    createdAt: "04월 09일",
  },
  {
    id: "r44",
    to: "친구에게",
    from: "동기",
    preview: "술 한잔하자",
    content: "술 한잔하자.\n\n요즘 고민이 많아서 그래. 시간 괜찮은 날 알려줘.",
    keyword: "감사",
    theme: 4,
    createdAt: "04월 18일",
  },
  {
    id: "r45",
    to: "멘토님에게",
    from: "제자",
    preview: "덕분에 자신감이 생겼어요",
    content:
      "덕분에 자신감이 생겼어요.\n\n부족한 점을 잘 짚어주셔서 감사합니다. 더 노력할게요!",
    keyword: "생일",
    theme: 1,
    createdAt: "04월 22일",
  },
  {
    id: "r46",
    to: "부모님께",
    from: "아들",
    preview: "설날에 뵐게요",
    content:
      "설날에 뵐게요.\n\n가서 맛있는 거 많이 먹고 오겠습니다. 건강하세요!",
    keyword: "감사",
    theme: 3,
    createdAt: "04월 01일",
  },
  {
    id: "r47",
    to: "친구에게",
    from: "너의친구",
    preview: "공부하느라 고생이 많다",
    content:
      "공부하느라 고생이 많다.\n\n너무 앞만 보고 달리지 마. 가끔은 쉬어 가도 괜찮아.",
    keyword: "생일",
    theme: 2,
    createdAt: "04월 06일",
  },
  {
    id: "r48",
    to: "짝꿍에게",
    from: "마음",
    preview: "시험 망쳤어...",
    content:
      "시험 망쳤어...\n\n위로해 줄 사람 너밖에 없다. 저녁에 잠깐 볼 수 있어?",
    keyword: "감사",
    theme: 4,
    createdAt: "04월 13일",
  },
  {
    id: "r49",
    to: "동료에게",
    from: "팀원",
    preview: "휴가 잘 다녀와",
    content:
      "휴가 잘 다녀와.\n\n업무는 내가 잘 보고 있을게. 걱정 말고 푹 쉬다 와!",
    keyword: "생일",
    theme: 1,
    createdAt: "04월 17일",
  },
  {
    id: "r50",
    to: "친구에게",
    from: "단짝",
    preview: "나 합격했어!",
    content: "나 합격했어!\n\n다 너 덕분이야. 우리 파티하자! 너무 신나!",
    keyword: "감사",
    theme: 3,
    createdAt: "04월 29일",
  },
  {
    id: "r51",
    to: "선배님에게",
    from: "후배",
    preview: "항상 감사합니다",
    content: "항상 감사합니다.\n\n부족한 저를 항상 챙겨주셔서 큰 힘이 돼요.",
    keyword: "생일",
    theme: 2,
    createdAt: "04월 04일",
  },
  {
    id: "r52",
    to: "연인에게",
    from: "자기야",
    preview: "사랑해",
    content: "사랑해.\n\n무슨 일이 있어도 네 편일게. 우리 예쁘게 만나자.",
    keyword: "감사",
    theme: 4,
    createdAt: "04월 10일",
  },
  {
    id: "r53",
    to: "동생에게",
    from: "언니",
    preview: "옷 좀 그만 사",
    content: "옷 좀 그만 사.\n\n언니 지갑 다 털리겠다. 그래도 예쁘니까 참는다.",
    keyword: "생일",
    theme: 1,
    createdAt: "04월 07일",
  },
  {
    id: "r54",
    to: "친구에게",
    from: "베프",
    preview: "생일 축하한다",
    content: "생일 축하한다.\n\n태어나줘서 고맙고, 늙어서도 같이 떡볶이 먹자.",
    keyword: "감사",
    theme: 3,
    createdAt: "04월 24일",
  },
  {
    id: "r55",
    to: "부모님께",
    from: "딸",
    preview: "선물 보냈어요",
    content:
      "선물 보냈어요.\n\n좋아하실지 모르겠네요. 다음엔 더 좋은 거 해드릴게요.",
    keyword: "생일",
    theme: 2,
    createdAt: "04월 26일",
  },
  {
    id: "r56",
    to: "소중한 당신에게",
    from: "나",
    preview: "오늘 하루 정말 고생했어",
    content:
      "오늘 하루 정말 고생했어.\n\n너보다 더 잘할 수 있는 사람은 없어. 조금만 더 힘내자.",
    keyword: "감사",
    theme: 4,
    createdAt: "04월 05일",
  },
  {
    id: "r57",
    to: "동료에게",
    from: "동기",
    preview: "야근 실화냐",
    content:
      "야근 실화냐.\n\n끝나고 맥주 한잔 때리러 가자. 지금 너무 피곤하다.",
    keyword: "생일",
    theme: 1,
    createdAt: "04월 14일",
  },
  {
    id: "r58",
    to: "친구에게",
    from: "너의벗",
    preview: "결혼 축하해!",
    content: "결혼 축하해!\n\n드디어 가는구나. 행복하게 잘 살아라! 부럽다!",
    keyword: "감사",
    theme: 3,
    createdAt: "04월 21일",
  },
  {
    id: "r59",
    to: "선생님에게",
    from: "제자",
    preview: "건강하세요",
    content:
      "건강하세요.\n\n환절기라 감기 걸리시기 딱 좋아요. 꼭 따뜻하게 입으세요.",
    keyword: "생일",
    theme: 2,
    createdAt: "04월 12일",
  },
  {
    id: "r60",
    to: "가족에게",
    from: "아빠",
    preview: "딸 공부 열심해",
    content: "딸 공부 열심해.\n\n너무 무리하지 말고. 아빠는 항상 응원한다.",
    keyword: "감사",
    theme: 4,
    createdAt: "04월 16일",
  },
  {
    id: "r61",
    to: "친구에게",
    from: "단짝",
    preview: "오늘 시간 돼?",
    content: "오늘 시간 돼?\n\n급한 일은 아닌데 그냥 얼굴 보고 싶어서 그래.",
    keyword: "생일",
    theme: 1,
    createdAt: "04월 23일",
  },
  {
    id: "r62",
    to: "멘토님에게",
    from: "제자",
    preview: "감사합니다",
    content:
      "감사합니다.\n\n선생님 조언 덕분에 새로운 길을 찾았어요. 감사합니다.",
    keyword: "감사",
    theme: 3,
    createdAt: "04월 02일",
  },
  {
    id: "r63",
    to: "짝꿍에게",
    from: "마음",
    preview: "오늘 급식 맛있더라",
    content: "오늘 급식 맛있더라.\n\n너도 먹었어? 다음엔 같이 줄 서서 먹자.",
    keyword: "생일",
    theme: 2,
    createdAt: "04월 27일",
  },
  {
    id: "r64",
    to: "연인에게",
    from: "사랑꾼",
    preview: "잠시만 생각날 때",
    content:
      "잠시만 생각날 때 연락해.\n\n난 항상 네 연락 기다리고 있으니까. 사랑해.",
    keyword: "감사",
    theme: 4,
    createdAt: "04월 08일",
  },
  {
    id: "r65",
    to: "친구에게",
    from: "베프",
    preview: "우리 다음 여행 어디 갈까?",
    content: "우리 다음 여행 어디 갈까?\n\n벌써 설렌다. 이번엔 좀 멀리 가볼까?",
    keyword: "생일",
    theme: 1,
    createdAt: "04월 19일",
  },
  {
    id: "r66",
    to: "후배에게",
    from: "선배",
    preview: "과제 다 했니?",
    content: "과제 다 했니?\n\n마감 시간 얼마 안 남았어. 빨리해서 제출해!",
    keyword: "감사",
    theme: 3,
    createdAt: "04월 10일",
  },
  {
    id: "r67",
    to: "지인에게",
    from: "고마운이",
    preview: "생일 챙겨줘서 고마워",
    content: "생일 챙겨줘서 고마워.\n\n덕분에 행복한 하루 보냈어. 나중에 보자!",
    keyword: "생일",
    theme: 2,
    createdAt: "04월 28일",
  },
  {
    id: "r68",
    to: "나에게",
    from: "미래의나",
    preview: "포기하지 마",
    content:
      "포기하지 마.\n\n지금 하는 고민들이 나중에 다 자산이 될 거야. 힘내.",
    keyword: "감사",
    theme: 4,
    createdAt: "04월 15일",
  },
  {
    id: "r69",
    to: "친구에게",
    from: "동기",
    preview: "과제 같이 하자",
    content: "과제 같이 하자.\n\n혼자 하려니까 너무 막막하다. 도서관에서 만나.",
    keyword: "생일",
    theme: 1,
    createdAt: "04월 04일",
  },
  {
    id: "r70",
    to: "부모님께",
    from: "딸",
    preview: "사랑해요",
    content:
      "사랑해요.\n\n어버이날에 제대로 효도할게요. 맛있는 거 먹으러 가요!",
    keyword: "감사",
    theme: 3,
    createdAt: "04월 06일",
  },
  {
    id: "r71",
    to: "동료에게",
    from: "팀원",
    preview: "발표 무사히 끝났다!",
    content: "발표 무사히 끝났다!\n\n진짜 고생 많았어. 이제 우리 좀 쉬자!",
    keyword: "생일",
    theme: 2,
    createdAt: "04월 13일",
  },
  {
    id: "r72",
    to: "연인에게",
    from: "자기야",
    preview: "오늘 너무 좋았어",
    content: "오늘 너무 좋았어.\n\n나랑 만나줘서 고마워. 우리 오래오래 가자.",
    keyword: "감사",
    theme: 4,
    createdAt: "04월 25일",
  },
  {
    id: "r73",
    to: "친구에게",
    from: "베프",
    preview: "오늘 왜 안 나와?",
    content: "오늘 왜 안 나와?\n\n다들 기다리고 있는데. 빨리 와!",
    keyword: "생일",
    theme: 1,
    createdAt: "04월 20일",
  },
  {
    id: "r74",
    to: "선배님에게",
    from: "후배",
    preview: "조언 감사합니다",
    content:
      "조언 감사합니다.\n\n확실히 말씀해 주시니까 감이 잡히네요. 열심히 할게요!",
    keyword: "감사",
    theme: 3,
    createdAt: "04월 30일",
  },
  {
    id: "r75",
    to: "동생에게",
    from: "언니",
    preview: "학교 잘 다녀와",
    content: "학교 잘 다녀와.\n\n오늘 날씨 춥다니까 목도리 꼭 하고. 알았지?",
    keyword: "생일",
    theme: 2,
    createdAt: "04월 09일",
  },
  {
    id: "r76",
    to: "친구에게",
    from: "단짝",
    preview: "우리 10년지기",
    content: "우리 10년지기.\n\n시간 참 빠르다. 앞으로도 내 옆에 있어줘!",
    keyword: "감사",
    theme: 4,
    createdAt: "04월 21일",
  },
  {
    id: "r77",
    to: "부모님께",
    from: "아들",
    preview: "감사합니다",
    content:
      "감사합니다.\n\n항상 응원해 주셔서 힘이 납니다. 조만간 찾아뵐게요.",
    keyword: "생일",
    theme: 1,
    createdAt: "04월 17일",
  },
  {
    id: "r78",
    to: "소중한 당신에게",
    from: "친구",
    preview: "비 온다",
    content: "비 온다.\n\n운치 있다 그치? 이런 날은 파전에 막걸리인데!",
    keyword: "감사",
    theme: 3,
    createdAt: "04월 18일",
  },
  {
    id: "r79",
    to: "멘토님에게",
    from: "제자",
    preview: "항상 응원합니다",
    content: "항상 응원합니다.\n\n저도 선생님처럼 멋진 사람이 되고 싶어요.",
    keyword: "생일",
    theme: 2,
    createdAt: "04월 01일",
  },
  {
    id: "r80",
    to: "나에게",
    from: "오늘의나",
    preview: "오늘 하루도 버텼다",
    content:
      "오늘 하루도 버텼다.\n\n너무 애썼어. 내일은 좀 더 여유롭게 보내자!",
    keyword: "감사",
    theme: 4,
    createdAt: "04월 11일",
  },
];
