// TODO: API 연동 후 제거
import type { LetterItem } from "../shared/schemas/letterSchema";

export const MOCK_SENT: LetterItem[] = [
  {
    id: "1",
    to: "소중한 친구",
    from: "마음을 담아",
    preview: "진심으로 생일 축하해! 오늘 하루는...",
    content:
      "오늘 너의 생일을 진심으로 축하해.\n\n벌써 이렇게 또 한 해가 지나갔다는 게 신기하기도 하고, 그만큼 우리가 함께한 시간이 쌓였다는 게 새삼 감사하게 느껴져.\n\n네가 내 곁에 있어줘서 얼마나 든든한지 몰라. 오늘 하루만큼은 네가 세상에서 제일 특별한 사람이라는 걸 느꼈으면 좋겠어. 생일 축하해! 🎂✨",
    keyword: "생일",
    theme: 1,
    createdAt: "04월 22일",
  },
  {
    id: "2",
    to: "엄마",
    from: "마음을 담아",
    preview: "항상 저를 위해 애써주셔서 감사...",
    content:
      "항상 저를 위해 애써주셔서 감사드려요. 엄마 덕분에 제가 이렇게 잘 자랄 수 있었어요.",
    keyword: "감사",
    theme: 2,
    createdAt: "04월 15일",
  },
  {
    id: "3",
    to: "가장 친한 친구",
    from: "마음을 담아",
    preview: "생일 축하한다 친구야!",
    content:
      "생일 정말 축하해! 우리가 알고 지낸 지 벌써 몇 년인지 모르겠다. 앞으로도 지금처럼 변치 말고 같이 재미있게 지내자.",
    keyword: "생일",
    theme: 3,
    createdAt: "04월 01일",
  },
  {
    id: "4",
    to: "선생님",
    from: "마음을 담아",
    preview: "가르침에 진심으로 감사드립니다.",
    content:
      "선생님, 그동안 저희를 이끌어주시고 가르쳐 주셔서 정말 감사합니다. 선생님의 따뜻한 조언 덕분에 많은 것을 배웠어요.",
    keyword: "감사",
    theme: 4,
    createdAt: "04월 02일",
  },
  {
    id: "5",
    to: "사랑하는 아빠",
    from: "마음을 담아",
    preview: "아빠 생신 축하드려요!",
    content:
      "아빠, 생신 진심으로 축하드려요! 늘 묵묵히 저희를 위해 고생하시는 아빠를 존경해요. 오래오래 건강하세요!",
    keyword: "생일",
    theme: 1,
    createdAt: "04월 03일",
  },
  {
    id: "6",
    to: "직장 동료",
    from: "마음을 담아",
    preview: "도와주셔서 큰 힘이 됐습니다.",
    content:
      "지난번 프로젝트 때 정말 많이 도와주셔서 감사합니다. 동료님 덕분에 무사히 끝낼 수 있었어요. 정말 고마워요.",
    keyword: "감사",
    theme: 2,
    createdAt: "04월 04일",
  },
  {
    id: "7",
    to: "동생",
    from: "마음을 담아",
    preview: "내 동생 생일 축하해!",
    content:
      "어느새 이렇게 훌쩍 커버린 우리 동생, 생일 정말 축하해! 하고 싶은 거 다 이루는 한 해가 되길 바라.",
    keyword: "생일",
    theme: 3,
    createdAt: "04월 05일",
  },
  {
    id: "8",
    to: "선배",
    from: "마음을 담아",
    preview: "좋은 가르침 감사합니다.",
    content:
      "선배님, 지난번 고민 상담해주신 덕분에 마음이 한결 가벼워졌어요. 진심으로 감사드립니다.",
    keyword: "감사",
    theme: 4,
    createdAt: "04월 06일",
  },
  {
    id: "9",
    to: "연인",
    from: "마음을 담아",
    preview: "태어나줘서 고마워!",
    content:
      "오늘 네 생일이라니 너무 기뻐. 너를 만난 건 내 인생 최고의 행운이야. 세상에서 가장 행복한 생일 보내길 바라.",
    keyword: "생일",
    theme: 1,
    createdAt: "04월 07일",
  },
  {
    id: "10",
    to: "이웃분",
    from: "마음을 담아",
    preview: "항상 챙겨주셔서 감사해요.",
    content:
      "항상 저희 가족 챙겨주셔서 감사합니다. 덕분에 따뜻한 정을 느끼고 있어요. 항상 건강하세요!",
    keyword: "감사",
    theme: 2,
    createdAt: "04월 08일",
  },
  {
    id: "11",
    to: "친구",
    from: "마음을 담아",
    preview: "생일 진심으로 축하해!",
    content:
      "생일 축하한다! 올해는 네가 원하는 일 모두 다 이뤄지는 최고의 한 해가 되길 바랄게.",
    keyword: "생일",
    theme: 3,
    createdAt: "04월 09일",
  },
  {
    id: "12",
    to: "멘토님",
    from: "마음을 담아",
    preview: "덕분에 잘 성장하고 있습니다.",
    content:
      "멘토님, 제가 흔들릴 때마다 잡아주셔서 감사합니다. 덕분에 올바른 방향으로 나아가고 있어요.",
    keyword: "감사",
    theme: 4,
    createdAt: "04월 10일",
  },
  {
    id: "13",
    to: "소중한 사람",
    from: "마음을 담아",
    preview: "생일 축하해요!",
    content:
      "오늘 이렇게 특별한 날을 맞이한 당신, 정말 생일 축하해요! 오늘 하루가 당신에게 가장 행복한 기억이 되길 바라요.",
    keyword: "생일",
    theme: 1,
    createdAt: "04월 11일",
  },
  {
    id: "14",
    to: "파트너",
    from: "마음을 담아",
    preview: "함께해주셔서 감사합니다.",
    content:
      "함께해주셔서 감사합니다. 당신이 옆에 있어서 얼마나 다행인지 몰라요. 앞으로도 잘 부탁드립니다.",
    keyword: "감사",
    theme: 2,
    createdAt: "04월 12일",
  },
  {
    id: "15",
    to: "단짝친구",
    from: "마음을 담아",
    preview: "생일 축하해 우리 단짝!",
    content:
      "우와, 오늘 네 생일이네! 태어나줘서 고맙고, 우리 늙어서도 같이 놀자. 정말 축하해!",
    keyword: "생일",
    theme: 3,
    createdAt: "04월 13일",
  },
  {
    id: "16",
    to: "후배",
    from: "마음을 담아",
    preview: "열심히 해줘서 고마워.",
    content:
      "항상 자기 일 열심히 해줘서 정말 고마워. 너 같은 후배를 둬서 정말 다행이야. 고생 많았어!",
    keyword: "감사",
    theme: 4,
    createdAt: "04월 14일",
  },
  {
    id: "17",
    to: "가족",
    from: "마음을 담아",
    preview: "생일 축하해!",
    content:
      "가족이라서가 아니라, 정말 한 사람으로서 너의 생일을 축하해! 늘 사랑해!",
    keyword: "생일",
    theme: 1,
    createdAt: "04월 15일",
  },
  {
    id: "18",
    to: "사장님",
    from: "마음을 담아",
    preview: "믿어주셔서 감사합니다.",
    content:
      "저를 믿고 중요한 업무 맡겨주셔서 감사합니다. 기대에 부응할 수 있도록 노력하겠습니다.",
    keyword: "감사",
    theme: 2,
    createdAt: "04월 16일",
  },
  {
    id: "19",
    to: "동기",
    from: "마음을 담아",
    preview: "생일 축하한다 동기야!",
    content:
      "우와 오늘 생일이네? 바빠도 맛있는 거 꼭 챙겨 먹고 즐거운 하루 보내라!",
    keyword: "생일",
    theme: 3,
    createdAt: "04월 17일",
  },
  {
    id: "20",
    to: "부모님",
    from: "마음을 담아",
    preview: "길러주셔서 감사합니다.",
    content:
      "저를 지금까지 사랑으로 길러주셔서 감사합니다. 그 은혜에 보답할 수 있는 자식이 되도록 할게요.",
    keyword: "감사",
    theme: 4,
    createdAt: "04월 18일",
  },
  {
    id: "21",
    to: "언니",
    from: "마음을 담아",
    preview: "생일 축하해 언니!",
    content:
      "언니 생일 축하해! 늘 내 편이 되어줘서 고마워. 오늘도 행복한 하루 보내!",
    keyword: "생일",
    theme: 1,
    createdAt: "04월 19일",
  },
  {
    id: "22",
    to: "친구",
    from: "마음을 담아",
    preview: "도와줘서 정말 고마워.",
    content:
      "어제 정말 고마웠어. 너 없었으면 큰일 날 뻔했어. 다음에 내가 꼭 보답할게!",
    keyword: "감사",
    theme: 2,
    createdAt: "04월 20일",
  },
  {
    id: "23",
    to: "오빠",
    from: "마음을 담아",
    preview: "생일 축하해요 오빠!",
    content:
      "오빠 생일 축하해요! 오늘 하루는 걱정 근심 다 잊고 행복하게 보냈으면 좋겠어요.",
    keyword: "생일",
    theme: 3,
    createdAt: "04월 21일",
  },
  {
    id: "24",
    to: "팀장님",
    from: "마음을 담아",
    preview: "항상 이끌어주셔서 감사합니다.",
    content:
      "팀장님, 항상 열정적으로 이끌어주셔서 감사합니다. 팀장님을 보면서 참 많이 배워요.",
    keyword: "감사",
    theme: 4,
    createdAt: "04월 22일",
  },
  {
    id: "25",
    to: "친구",
    from: "마음을 담아",
    preview: "생일 축하하고 맛있는 거 먹자!",
    content:
      "오늘 생일 진심으로 축하해! 케이크 맛있게 먹고 오늘 하루 주인공처럼 보내길 바라!",
    keyword: "생일",
    theme: 1,
    createdAt: "04월 23일",
  },
  {
    id: "26",
    to: "은사님",
    from: "마음을 담아",
    preview: "잊지 않고 감사드립니다.",
    content:
      "선생님, 제가 사회에 나가서도 선생님의 가르침 잊지 않고 살고 있습니다. 진심으로 감사드려요.",
    keyword: "감사",
    theme: 2,
    createdAt: "04월 24일",
  },
  {
    id: "27",
    to: "지인",
    from: "마음을 담아",
    preview: "생일 축하합니다!",
    content:
      "오늘 생일 축하합니다! 늘 좋은 일만 가득한 날들 보내시길 기원할게요.",
    keyword: "생일",
    theme: 3,
    createdAt: "04월 25일",
  },
  {
    id: "28",
    to: "배우자",
    from: "마음을 담아",
    preview: "함께해줘서 감사합니다.",
    content:
      "여보, 늘 우리 가족을 위해 헌신해줘서 정말 감사합니다. 당신이 있어서 정말 행복해요.",
    keyword: "감사",
    theme: 4,
    createdAt: "04월 26일",
  },
  {
    id: "29",
    to: "베프",
    from: "마음을 담아",
    preview: "생일 축하해 내 친구!",
    content:
      "우리 벌써 몇 년째 생일 챙겨주는 거지? 늘 고맙고 생일 진심으로 축하해!",
    keyword: "생일",
    theme: 1,
    createdAt: "04월 27일",
  },
  {
    id: "30",
    to: "조언자",
    from: "마음을 담아",
    preview: "진심 어린 조언 감사합니다.",
    content:
      "힘들 때마다 해주시는 진심 어린 조언 덕분에 큰 용기를 얻습니다. 정말 감사합니다.",
    keyword: "감사",
    theme: 2,
    createdAt: "04월 28일",
  },
  {
    id: "31",
    to: "동생",
    from: "마음을 담아",
    preview: "생일 축하해!",
    content: "동생아 생일 축하한다! 오늘 하루 세상에서 가장 즐겁게 보내라!",
    keyword: "생일",
    theme: 3,
    createdAt: "04월 29일",
  },
  {
    id: "32",
    to: "직장 동료",
    from: "마음을 담아",
    preview: "함께 근무해서 감사합니다.",
    content:
      "함께 근무하게 되어서 정말 영광이고 감사합니다. 덕분에 즐겁게 일하고 있어요.",
    keyword: "감사",
    theme: 4,
    createdAt: "04월 30일",
  },
  {
    id: "33",
    to: "소중한 사람",
    from: "마음을 담아",
    preview: "생일 진심으로 축하해요.",
    content:
      "당신의 생일을 진심으로 축하해요. 당신이 태어난 오늘이 나에게는 가장 행복한 날이에요.",
    keyword: "생일",
    theme: 1,
    createdAt: "04월 01일",
  },
  {
    id: "34",
    to: "고마운 친구",
    from: "마음을 담아",
    preview: "변함없는 우정 감사합니다.",
    content:
      "언제나 한결같이 내 곁을 지켜줘서 감사합니다. 너 같은 친구가 있다는 게 참 다행이야.",
    keyword: "감사",
    theme: 2,
    createdAt: "04월 02일",
  },
  {
    id: "35",
    to: "후배",
    from: "마음을 담아",
    preview: "생일 축하한다 후배야!",
    content:
      "오늘 생일 축하해! 앞으로 더 멋진 사람이 되길 응원할게. 좋은 하루 보내!",
    keyword: "생일",
    theme: 3,
    createdAt: "04월 03일",
  },
  {
    id: "36",
    to: "선배",
    from: "마음을 담아",
    preview: "가르침에 감사합니다.",
    content:
      "선배님, 늘 저를 아껴주시고 좋은 가르침 주셔서 감사합니다. 배우는 게 참 많아요.",
    keyword: "감사",
    theme: 4,
    createdAt: "04월 04일",
  },
  {
    id: "37",
    to: "친구",
    from: "마음을 담아",
    preview: "생일 축하해!",
    content:
      "오늘 생일인데 맛있는 거 많이 먹고 행복한 하루 보내! 생일 진심으로 축하해.",
    keyword: "생일",
    theme: 1,
    createdAt: "04월 05일",
  },
  {
    id: "38",
    to: "동료",
    from: "마음을 담아",
    preview: "배려해주셔서 감사합니다.",
    content:
      "업무 중에 배려해주셔서 정말 감사합니다. 덕분에 수월하게 일했어요.",
    keyword: "감사",
    theme: 2,
    createdAt: "04월 06일",
  },
  {
    id: "39",
    to: "사랑하는 사람",
    from: "마음을 담아",
    preview: "생일 축하해요.",
    content:
      "당신이 세상에 태어나줘서 고마워요. 생일 진심으로 축하하고 오늘도 사랑해요.",
    keyword: "생일",
    theme: 3,
    createdAt: "04월 07일",
  },
  {
    id: "40",
    to: "멘토님",
    from: "마음을 담아",
    preview: "늘 신경 써주셔서 감사합니다.",
    content:
      "늘 저를 잊지 않고 신경 써주셔서 감사합니다. 멘토님의 기대에 어긋나지 않는 사람이 될게요.",
    keyword: "감사",
    theme: 4,
    createdAt: "04월 08일",
  },
  {
    id: "41",
    to: "가족",
    from: "마음을 담아",
    preview: "생일 축하해!",
    content: "우리 가족 중 가장 특별한 날이네! 생일 축하하고 건강하게 지내자.",
    keyword: "생일",
    theme: 1,
    createdAt: "04월 09일",
  },
  {
    id: "42",
    to: "지인",
    from: "마음을 담아",
    preview: "베풀어주신 친절 감사합니다.",
    content:
      "지난번 베풀어주신 친절에 정말 감사합니다. 어떻게 보답해야 할지 모르겠네요.",
    keyword: "감사",
    theme: 2,
    createdAt: "04월 10일",
  },
  {
    id: "43",
    to: "친구",
    from: "마음을 담아",
    preview: "생일 축하해 친구야!",
    content:
      "어느덧 생일이네! 생일 축하하고 우리 조만간 보자! 즐거운 하루 보내!",
    keyword: "생일",
    theme: 3,
    createdAt: "04월 11일",
  },
  {
    id: "44",
    to: "후배",
    from: "마음을 담아",
    preview: "열심히 해주어 감사합니다.",
    content:
      "항상 묵묵히 제 뒤에서 열심히 해주어 정말 감사합니다. 덕분에 힘이 많이 나요.",
    keyword: "감사",
    theme: 4,
    createdAt: "04월 12일",
  },
  {
    id: "45",
    to: "사랑하는 동생",
    from: "마음을 담아",
    preview: "생일 축하해!",
    content:
      "우리 귀염둥이 동생 생일 축하해! 갖고 싶다던 거 샀어. 오늘 하루 신나게 놀아라!",
    keyword: "생일",
    theme: 1,
    createdAt: "04월 13일",
  },
  {
    id: "46",
    to: "동기",
    from: "마음을 담아",
    preview: "함께해주어 감사합니다.",
    content:
      "입사 동기로서 함께해주어 감사합니다. 서로 의지할 수 있어서 정말 다행이에요.",
    keyword: "감사",
    theme: 2,
    createdAt: "04월 14일",
  },
  {
    id: "47",
    to: "선생님",
    from: "마음을 담아",
    preview: "생신 축하드려요!",
    content:
      "선생님, 생신 진심으로 축하드려요! 건강하게 오래오래 저희 곁에 계셔주세요.",
    keyword: "생일",
    theme: 3,
    createdAt: "04월 15일",
  },
  {
    id: "48",
    to: "부모님",
    from: "마음을 담아",
    preview: "모든 것에 감사합니다.",
    content:
      "엄마 아빠, 저를 위해 희생하신 모든 것에 감사합니다. 정말 사랑합니다.",
    keyword: "감사",
    theme: 4,
    createdAt: "04월 16일",
  },
  {
    id: "49",
    to: "친구",
    from: "마음을 담아",
    preview: "생일 축하한다!",
    content:
      "생일 정말 축하한다. 네가 있어서 세상이 더 즐거워! 행복한 하루 돼라.",
    keyword: "생일",
    theme: 1,
    createdAt: "04월 17일",
  },
  {
    id: "50",
    to: "선배",
    from: "마음을 담아",
    preview: "조언 감사합니다.",
    content: "어려운 상황에서 해주신 조언 정말 감사합니다. 큰 도움이 되었어요.",
    keyword: "감사",
    theme: 2,
    createdAt: "04월 18일",
  },
  {
    id: "51",
    to: "사랑하는 오빠",
    from: "마음을 담아",
    preview: "생일 축하해요 오빠!",
    content:
      "오빠 생일 축하해! 오늘 하루는 맛있는 거 먹고 행복하게 보내길 바라.",
    keyword: "생일",
    theme: 3,
    createdAt: "04월 19일",
  },
  {
    id: "52",
    to: "동료",
    from: "마음을 담아",
    preview: "함께 일해서 감사합니다.",
    content:
      "같은 팀에서 함께 일해서 감사합니다. 동료님 덕분에 항상 즐겁게 일해요.",
    keyword: "감사",
    theme: 4,
    createdAt: "04월 20일",
  },
  {
    id: "53",
    to: "친구",
    from: "마음을 담아",
    preview: "생일 축하해!",
    content:
      "생일 진짜 축하한다. 우리 나이 먹어도 지금처럼 지내자! 오늘 하루 즐겨!",
    keyword: "생일",
    theme: 1,
    createdAt: "04월 21일",
  },
  {
    id: "54",
    to: "멘토",
    from: "마음을 담아",
    preview: "이끌어주셔서 감사합니다.",
    content: "저를 이끌어주시고 격려해주셔서 감사합니다. 정말 큰 힘이 됩니다.",
    keyword: "감사",
    theme: 2,
    createdAt: "04월 22일",
  },
  {
    id: "55",
    to: "언니",
    from: "마음을 담아",
    preview: "생일 축하해요 언니!",
    content:
      "언니 생일 축하해요! 예쁜 케이크 사고 갈게요. 오늘 하루 행복하게 보내요.",
    keyword: "생일",
    theme: 3,
    createdAt: "04월 23일",
  },
  {
    id: "56",
    to: "고마운 분",
    from: "마음을 담아",
    preview: "늘 고맙습니다.",
    content:
      "항상 따뜻하게 대해주셔서 감사합니다. 덕분에 마음이 참 따뜻해져요.",
    keyword: "감사",
    theme: 4,
    createdAt: "04월 24일",
  },
  {
    id: "57",
    to: "소중한 친구",
    from: "마음을 담아",
    preview: "생일 축하해!",
    content:
      "오늘 생일 진심으로 축하한다. 너만큼 특별한 사람 없다는 거 알지? 행복한 하루 보내!",
    keyword: "생일",
    theme: 1,
    createdAt: "04월 25일",
  },
  {
    id: "58",
    to: "가족",
    from: "마음을 담아",
    preview: "항상 감사합니다.",
    content: "어떤 순간에도 내 편이 되어줘서 감사합니다. 정말 사랑해요.",
    keyword: "감사",
    theme: 2,
    createdAt: "04월 26일",
  },
  {
    id: "59",
    to: "동생",
    from: "마음을 담아",
    preview: "생일 축하한다!",
    content:
      "동생아 생일 축하해! 앞으로도 건강하게 지내고 원하는 꿈 다 이루길 바라.",
    keyword: "생일",
    theme: 3,
    createdAt: "04월 27일",
  },
  {
    id: "60",
    to: "친구",
    from: "마음을 담아",
    preview: "함께해줘서 고마워.",
    content:
      "항상 내 옆에 있어줘서 정말 감사합니다. 너 같은 친구가 있다는 게 참 행운이야.",
    keyword: "감사",
    theme: 4,
    createdAt: "04월 28일",
  },
  {
    id: "61",
    to: "조카",
    from: "마음을 담아",
    preview: "생일 축하해!",
    content:
      "우리 조카 생일 축하해! 오늘 하루 최고로 행복하게 보내라! 삼촌이 많이 사랑해.",
    keyword: "생일",
    theme: 1,
    createdAt: "04월 29일",
  },
  {
    id: "62",
    to: "선배",
    from: "마음을 담아",
    preview: "항상 감사합니다.",
    content: "언제나 제가 성장할 수 있도록 도와주셔서 감사합니다. 존경합니다.",
    keyword: "감사",
    theme: 2,
    createdAt: "04월 30일",
  },
  {
    id: "63",
    to: "친구",
    from: "마음을 담아",
    preview: "생일 축하해 친구야!",
    content:
      "생일 축하한다 친구야! 오늘 생일인데 맛있는 거 많이 먹고 기분 좋은 하루 보내!",
    keyword: "생일",
    theme: 3,
    createdAt: "04월 01일",
  },
  {
    id: "64",
    to: "동료",
    from: "마음을 담아",
    preview: "배려 감사합니다.",
    content:
      "늘 제 입장 생각해주는 배려에 감사합니다. 같이 일할 수 있어서 행복해요.",
    keyword: "감사",
    theme: 4,
    createdAt: "04월 02일",
  },
  {
    id: "65",
    to: "사랑하는 사람",
    from: "마음을 담아",
    preview: "생일 축하해요!",
    content:
      "당신 생일 진심으로 축하해요. 함께하는 하루하루가 나에겐 선물이에요.",
    keyword: "생일",
    theme: 1,
    createdAt: "04월 03일",
  },
  {
    id: "66",
    to: "지인",
    from: "마음을 담아",
    preview: "정말 감사합니다.",
    content: "지난번에 해주신 도움 정말 감사합니다. 덕분에 잘 해결되었어요.",
    keyword: "감사",
    theme: 2,
    createdAt: "04월 04일",
  },
  {
    id: "67",
    to: "후배",
    from: "마음을 담아",
    preview: "생일 축하해!",
    content:
      "후배야 생일 축하해! 항상 열심히 하는 모습 보기 좋다. 오늘 즐겁게 보내!",
    keyword: "생일",
    theme: 3,
    createdAt: "04월 05일",
  },
  {
    id: "68",
    to: "멘토",
    from: "마음을 담아",
    preview: "진심으로 감사합니다.",
    content:
      "멘토님의 가르침에 진심으로 감사합니다. 멘토님 덕분에 여기까지 왔어요.",
    keyword: "감사",
    theme: 4,
    createdAt: "04월 06일",
  },
  {
    id: "69",
    to: "친구",
    from: "마음을 담아",
    preview: "생일 축하해!",
    content: "오늘 생일 축하해! 우리 떡볶이 먹으러 가자. 오늘 내가 쏠게!",
    keyword: "생일",
    theme: 1,
    createdAt: "04월 07일",
  },
  {
    id: "70",
    to: "가족",
    from: "마음을 담아",
    preview: "항상 감사합니다.",
    content: "우리 가족이라서 감사합니다. 늘 힘이 되어줘서 고마워요.",
    keyword: "감사",
    theme: 2,
    createdAt: "04월 08일",
  },
  {
    id: "71",
    to: "오빠",
    from: "마음을 담아",
    preview: "생일 축하해 오빠!",
    content:
      "오빠 생일 축하해! 우리 벌써 이렇게 컸네. 오늘 하루 맛있는 거 많이 먹고 즐겁게 보내.",
    keyword: "생일",
    theme: 3,
    createdAt: "04월 09일",
  },
  {
    id: "72",
    to: "동기",
    from: "마음을 담아",
    preview: "고마워.",
    content:
      "힘들 때마다 내 얘기 들어줘서 정말 감사합니다. 너 덕분에 이겨낼 수 있었어.",
    keyword: "감사",
    theme: 4,
    createdAt: "04월 10일",
  },
  {
    id: "73",
    to: "언니",
    from: "마음을 담아",
    preview: "생일 축하해요 언니!",
    content:
      "언니 생일 축하해요! 세상에서 제일 멋진 우리 언니, 오늘 행복한 날 보내세요.",
    keyword: "생일",
    theme: 1,
    createdAt: "04월 11일",
  },
  {
    id: "74",
    to: "친구",
    from: "마음을 담아",
    preview: "항상 감사합니다.",
    content: "내 옆에 있어줘서 정말 감사합니다. 너 같은 친구 있어서 참 든든해.",
    keyword: "감사",
    theme: 2,
    createdAt: "04월 12일",
  },
  {
    id: "75",
    to: "동생",
    from: "마음을 담아",
    preview: "생일 축하해!",
    content:
      "내 동생 생일 축하해! 오늘 하루 네가 세상에서 가장 행복하길 바랄게. 사랑해!",
    keyword: "생일",
    theme: 3,
    createdAt: "04월 13일",
  },
  {
    id: "76",
    to: "선배",
    from: "마음을 담아",
    preview: "감사합니다.",
    content: "저를 잘 이끌어주셔서 항상 감사합니다. 선배님 배려 잊지 않을게요.",
    keyword: "감사",
    theme: 4,
    createdAt: "04월 14일",
  },
  {
    id: "77",
    to: "소중한 친구",
    from: "마음을 담아",
    preview: "생일 축하해!",
    content:
      "내 친구 생일 축하해! 우리 앞으로도 오래오래 지금처럼 지내자! 사랑해!",
    keyword: "생일",
    theme: 1,
    createdAt: "04월 15일",
  },
  {
    id: "78",
    to: "지인",
    from: "마음을 담아",
    preview: "도움 감사합니다.",
    content:
      "덕분에 잘 해결되었어요. 정말 감사합니다. 나중에 제가 꼭 대접할게요.",
    keyword: "감사",
    theme: 2,
    createdAt: "04월 16일",
  },
  {
    id: "79",
    to: "엄마",
    from: "마음을 담아",
    preview: "생신 축하드려요!",
    content: "엄마 생신 축하드려요! 제가 더 효도할게요. 오늘 맛있는 거 먹어요!",
    keyword: "생일",
    theme: 3,
    createdAt: "04월 17일",
  },
  {
    id: "80",
    to: "아빠",
    from: "마음을 담아",
    preview: "항상 감사합니다.",
    content:
      "늘 저를 지켜주셔서 감사합니다. 아빠 덕분에 제가 이렇게 잘 자랄 수 있었어요.",
    keyword: "감사",
    theme: 4,
    createdAt: "04월 18일",
  },
];
