import type { LetterItem } from "../shared/schemas/letterSchema";

export const MOCK_RECEIVED: LetterItem[] = [
  { id: "r1", to: "소중한 당신에게", from: "친구", preview: "생일 감사해!", content: "진심으로 생일 감사해! 오늘 하루 최고로 행복하게 보내.", keyword: "생일", theme: 1, createdAt: "04월 01일" },
  { id: "r2", to: "선생님에게", from: "제자", preview: "감사합니다", content: "선생님, 항상 가르침 주셔서 감사합니다. 건강하세요.", keyword: "감사", theme: 2, createdAt: "04월 01일" },
  { id: "r3", to: "엄마에게", from: "딸", preview: "감사해요", content: "엄마, 항상 곁에서 챙겨주셔서 고마워요. 감사합니다.", keyword: "감사", theme: 3, createdAt: "04월 02일" },
  { id: "r4", to: "동료에게", from: "동료", preview: "고생했어", content: "오늘 프로젝트 마무리하느라 고생 많았어. 내일 봐!", keyword: "응원", theme: 1, createdAt: "04월 02일" },
  { id: "r5", to: "친구에게", from: "친구", preview: "커피 한잔?", content: "요즘 바빠 보이네. 시간 되면 커피나 한잔하자.", keyword: "감사", theme: 2, createdAt: "04월 03일" },
  { id: "r6", to: "소중한 당신에게", from: "연인", preview: "보고 싶어", content: "오늘따라 더 보고 싶네. 얼른 퇴근하고 보자.", keyword: "감사", theme: 3, createdAt: "04월 03일" },
  { id: "r7", to: "선생님에게", from: "제자", preview: "스승의 날", content: "스승의 날을 맞아 연락드려요. 항상 감사드립니다.", keyword: "감사", theme: 1, createdAt: "04월 04일" },
  { id: "r8", to: "엄마에게", from: "아들", preview: "건강하세요", content: "날씨가 많이 따뜻해졌네요. 환절기 감기 조심하세요.", keyword: "감사", theme: 2, createdAt: "04월 04일" },
  { id: "r9", to: "친구에게", from: "친구", preview: "감사해!", content: "이번 합격 정말 감사해! 다 네가 노력한 결과야.", keyword: "감사", theme: 3, createdAt: "04월 05일" },
  { id: "r10", to: "동료에게", from: "동료", preview: "부탁드려요", content: "이번 보고서 관련해서 잠시 의논할 게 있어요.", keyword: "감사", theme: 1, createdAt: "04월 05일" },
  { id: "r11", to: "소중한 당신에게", from: "친구", preview: "오랜만이야", content: "잘 지내지? 오랜만에 얼굴 한번 보고 싶다.", keyword: "감사", theme: 2, createdAt: "04월 06일" },
  { id: "r12", to: "선생님에게", from: "제자", preview: "졸업했어요", content: "선생님 덕분에 무사히 졸업합니다. 정말 감사합니다!", keyword: "감사", theme: 3, createdAt: "04월 07일" },
  { id: "r13", to: "엄마에게", from: "딸", preview: "주말에 갈게", content: "이번 주말에 집에 갈게요. 맛있는 거 먹어요!", keyword: "감사", theme: 1, createdAt: "04월 07일" },
  { id: "r14", to: "동료에게", from: "동료", preview: "점심 어때?", content: "오늘 점심은 맛있는 거 먹으러 가요!", keyword: "감사", theme: 2, createdAt: "04월 08일" },
  { id: "r15", to: "친구에게", from: "친구", preview: "힘내!", content: "요즘 많이 힘들지? 조금만 더 힘내자, 다 잘될 거야.", keyword: "응원", theme: 3, createdAt: "04월 08일" },
  { id: "r16", to: "연인에게", from: "연인", preview: "고마워", content: "어제 챙겨줘서 정말 고마웠어. 덕분에 행복했어.", keyword: "감사", theme: 1, createdAt: "04월 09일" },
  { id: "r17", to: "소중한 당신에게", from: "지인", preview: "새해 복 많이", content: "올 한 해도 건강하고 행복한 일들만 가득하세요!", keyword: "감사", theme: 2, createdAt: "04월 09일" },
  { id: "r18", to: "선생님에게", from: "제자", preview: "근황 연락", content: "선생님, 저 취업했습니다! 다 선생님 덕분이에요.", keyword: "감사", theme: 3, createdAt: "04월 10일" },
  { id: "r19", to: "엄마에게", from: "아들", preview: "용돈 보냈어", content: "엄마, 이번 달 용돈 보냈어요. 맛있는 거 사 드세요.", keyword: "감사", theme: 1, createdAt: "04월 10일" },
  { id: "r20", to: "동료에게", from: "동료", preview: "회의 자료", content: "회의 자료 미리 공유드립니다. 확인 부탁해요.", keyword: "감사", theme: 2, createdAt: "04월 11일" },
  { id: "r21", to: "친구에게", from: "친구", preview: "영화 보자", content: "이번에 새로 나온 영화 평점 좋던데 보러 갈까?", keyword: "감사", theme: 3, createdAt: "04월 11일" },
  { id: "r22", to: "연인에게", from: "연인", preview: "감사해", content: "오늘따라 왜 이렇게 예뻐? 감사해.", keyword: "감사", theme: 1, createdAt: "04월 12일" },
  { id: "r23", to: "소중한 당신에게", from: "친구", preview: "생일 감사!", content: "생일 감사해! 오늘 주인공은 너야.", keyword: "생일", theme: 2, createdAt: "04월 12일" },
  { id: "r24", to: "선생님에게", from: "제자", preview: "선물 보냈어요", content: "작은 마음이지만 선물 보냈습니다. 받아주세요.", keyword: "감사", theme: 3, createdAt: "04월 13일" },
  { id: "r25", to: "엄마에게", from: "딸", preview: "보고 싶어", content: "전화 자주 못 해서 미안해요. 엄마 감사해.", keyword: "감사", theme: 1, createdAt: "04월 13일" },
  { id: "r26", to: "동료에게", from: "동료", preview: "커피 고마워", content: "오늘 커피 잘 마셨어! 진짜 고마워.", keyword: "감사", theme: 2, createdAt: "04월 14일" },
  { id: "r27", to: "친구에게", from: "친구", preview: "여행 가자", content: "올여름에 우리 제주도 여행 갈래?", keyword: "감사", theme: 3, createdAt: "04월 14일" },
  { id: "r28", to: "연인에게", from: "연인", preview: "데이트", content: "이번 주 토요일에 어디 갈지 정했어?", keyword: "감사", theme: 1, createdAt: "04월 15일" },
  { id: "r29", to: "소중한 당신에게", from: "지인", preview: "항상 응원해", content: "네가 하는 모든 일 항상 응원하고 있어.", keyword: "응원", theme: 2, createdAt: "04월 15일" },
  { id: "r30", to: "선생님에게", from: "제자", preview: "죄송해요", content: "연락이 늦었네요. 항상 건강하시길 빌어요.", keyword: "감사", theme: 3, createdAt: "04월 16일" },
  { id: "r31", to: "엄마에게", from: "아들", preview: "건강 챙기세요", content: "엄마, 비타민 꼭 챙겨 드세요. 아프지 마시고요.", keyword: "감사", theme: 1, createdAt: "04월 16일" },
  { id: "r32", to: "동료에게", from: "동료", preview: "야근?", content: "오늘 야근 안 하세요? 먼저 퇴근하겠습니다!", keyword: "감사", theme: 2, createdAt: "04월 17일" },
  { id: "r33", to: "친구에게", from: "친구", preview: "생일 파티", content: "이번 생일 파티 언제 할 거야? 기대된다!", keyword: "생일", theme: 3, createdAt: "04월 17일" },
  { id: "r34", to: "연인에게", from: "연인", preview: "꿈에 나왔어", content: "어제 꿈에 네가 나왔는데 너무 좋았어.", keyword: "감사", theme: 1, createdAt: "04월 18일" },
  { id: "r35", to: "소중한 당신에게", from: "친구", preview: "잘 지내지?", content: "매일 반복되는 감사이지만 힘내보자!", keyword: "응원", theme: 2, createdAt: "04월 18일" },
  { id: "r36", to: "선생님에게", from: "제자", preview: "감사해요", content: "선생님 덕분에 꿈을 찾았어요. 감사합니다.", keyword: "감사", theme: 3, createdAt: "04월 19일" },
  { id: "r37", to: "엄마에게", from: "딸", preview: "감사해요", content: "세상에서 제일 감사하는 엄마, 항상 고마워요.", keyword: "감사", theme: 1, createdAt: "04월 19일" },
  { id: "r38", to: "동료에게", from: "동료", preview: "워크숍", content: "다음 주 워크숍 준비는 잘 되어가나요?", keyword: "감사", theme: 2, createdAt: "04월 20일" },
  { id: "r39", to: "친구에게", from: "친구", preview: "같이 가자", content: "이번 전시회 정말 가보고 싶었는데 같이 가자!", keyword: "감사", theme: 3, createdAt: "04월 20일" },
  { id: "r40", to: "연인에게", from: "연인", preview: "1주년", content: "우리 벌써 1주년이네? 앞으로도 잘 부탁해.", keyword: "감사", theme: 1, createdAt: "04월 21일" },
  { id: "r41", to: "소중한 당신에게", from: "친구", preview: "힘든 일 있니", content: "목소리 보니까 힘든 거 같은데, 무슨 일 있어?", keyword: "응원", theme: 2, createdAt: "04월 21일" },
  { id: "r42", to: "선생님에게", from: "제자", preview: "또 뵐게요", content: "조만간 찾아뵙겠습니다. 선생님 건강하세요!", keyword: "감사", theme: 3, createdAt: "04월 22일" },
  { id: "r43", to: "엄마에게", from: "아들", preview: "맛있는 거 먹자", content: "주말에 외식해요! 제가 맛집 예약할게요.", keyword: "감사", theme: 1, createdAt: "04월 22일" },
  { id: "r44", to: "동료에게", from: "동료", preview: "대박!", content: "이번 기획서 통과됐어! 진짜 대박이야.", keyword: "감사", theme: 2, createdAt: "04월 23일" },
  { id: "r45", to: "친구에게", from: "친구", preview: "생일 선물", content: "생일 선물 뭐 갖고 싶어? 미리 말해줘!", keyword: "생일", theme: 3, createdAt: "04월 23일" },
  { id: "r46", to: "연인에게", from: "연인", preview: "잘 자", content: "하루 마무리 잘하고, 꿈에서 보자. 감사해.", keyword: "감사", theme: 1, createdAt: "04월 24일" },
  { id: "r47", to: "소중한 당신에게", from: "친구", preview: "미안해", content: "어제는 내가 좀 예민했어. 미안해.", keyword: "감사", theme: 2, createdAt: "04월 24일" },
  { id: "r48", to: "선생님에게", from: "제자", preview: "감사합니다", content: "선생님의 조언 덕분에 큰 결정을 할 수 있었어요.", keyword: "감사", theme: 3, createdAt: "04월 25일" },
  { id: "r49", to: "엄마에게", from: "딸", preview: "꽃 선물", content: "꽃 좋아하시는 엄마 생각나서 보내요.", keyword: "감사", theme: 1, createdAt: "04월 25일" },
  { id: "r50", to: "동료에게", from: "동료", preview: "수고하세요", content: "먼저 퇴근합니다. 오늘 고생 많으셨어요!", keyword: "응원", theme: 2, createdAt: "04월 26일" },
  { id: "r51", to: "친구에게", from: "친구", preview: "감사해!", content: "이번 이직 정말 감사해! 더 좋은 곳으로 가네.", keyword: "감사", theme: 3, createdAt: "04월 26일" },
  { id: "r52", to: "연인에게", from: "연인", preview: "꽃 받았어", content: "보내준 꽃 정말 예뻐, 고마워 자기야.", keyword: "감사", theme: 1, createdAt: "04월 27일" },
  { id: "r53", to: "소중한 당신에게", from: "친구", preview: "언제 봐?", content: "너무 바쁘다 우리. 조만간 시간 좀 내보자.", keyword: "감사", theme: 2, createdAt: "04월 27일" },
  { id: "r54", to: "선생님에게", from: "제자", preview: "스승의 은혜", content: "항상 잊지 않고 있습니다. 존경합니다 선생님.", keyword: "감사", theme: 3, createdAt: "04월 28일" },
  { id: "r55", to: "엄마에게", from: "아들", preview: "감사해요", content: "엄마, 항상 건강 잘 챙기셔야 해요. 감사해요.", keyword: "감사", theme: 1, createdAt: "04월 28일" },
  { id: "r56", to: "동료에게", from: "동료", preview: "회의 시간", content: "오후 3시에 회의 있는 거 아시죠?", keyword: "감사", theme: 2, createdAt: "04월 29일" },
  { id: "r57", to: "친구에게", from: "친구", preview: "생일 감사해", content: "생일 감사해! 세상에서 제일 행복한 하루 보내!", keyword: "생일", theme: 3, createdAt: "04월 29일" },
  { id: "r58", to: "연인에게", from: "연인", preview: "보고 싶어", content: "일하다 보니까 네 생각이 많이 나네.", keyword: "감사", theme: 1, createdAt: "04월 30일" },
  { id: "r59", to: "소중한 당신에게", from: "지인", preview: "행복하길", content: "항상 너의 앞날을 응원하고 있어.", keyword: "응원", theme: 2, createdAt: "04월 30일" },
  { id: "r60", to: "선생님에게", from: "제자", preview: "감사한 마음", content: "글로 다 담을 수 없지만 정말 감사합니다.", keyword: "감사", theme: 3, createdAt: "05월 01일" },
  { id: "r61", to: "엄마에게", from: "딸", preview: "선물 도착했어?", content: "어제 보낸 영양제 도착했는지 모르겠네.", keyword: "감사", theme: 1, createdAt: "05월 01일" },
  { id: "r62", to: "동료에게", from: "동료", preview: "고마워", content: "오늘 도와줘서 진짜 고마웠어. 덕분에 끝냈네.", keyword: "감사", theme: 2, createdAt: "05월 02일" },
  { id: "r63", to: "친구에게", from: "친구", preview: "주말 어때?", content: "이번 주말에 집에만 있지 말고 나오자!", keyword: "감사", theme: 3, createdAt: "05월 02일" },
  { id: "r64", to: "연인에게", from: "연인", preview: "우리 결혼", content: "우리 이제 결혼하자. 평생 함께해줘.", keyword: "감사", theme: 1, createdAt: "05월 03일" },
  { id: "r65", to: "소중한 당신에게", from: "친구", preview: "잘 지내?", content: "요즘 어떤지 궁금해서 연락해봤어.", keyword: "감사", theme: 2, createdAt: "05월 03일" },
  { id: "r66", to: "선생님에게", from: "제자", preview: "존경합니다", content: "변함없이 학생들 아껴주시는 모습 존경합니다.", keyword: "감사", theme: 3, createdAt: "05월 03일" },
  { id: "r67", to: "엄마에게", from: "아들", preview: "전화할게", content: "오늘 일찍 들어가서 전화할게요!", keyword: "감사", theme: 1, createdAt: "05월 04일" },
  { id: "r68", to: "동료에게", from: "동료", preview: "점심은?", content: "오늘 점심 뭐 먹을까? 후보 좀 골라줘.", keyword: "감사", theme: 2, createdAt: "05월 04일" },
  { id: "r69", to: "친구에게", from: "친구", preview: "생일 감사해", content: "생일 너무 감사해! 오늘 케이크 먹자.", keyword: "생일", theme: 3, createdAt: "05월 04일" },
  { id: "r70", to: "연인에게", from: "연인", preview: "감사해요", content: "감사한다는 말로는 부족할 만큼 감사해.", keyword: "감사", theme: 1, createdAt: "05월 04일" },
  { id: "r71", to: "소중한 당신에게", from: "친구", preview: "화이팅", content: "오늘 하루도 화이팅! 할 수 있어.", keyword: "응원", theme: 2, createdAt: "05월 04일" },
  { id: "r72", to: "선생님에게", from: "제자", preview: "감사드려요", content: "언제나 건강하시길 기도할게요. 감사합니다.", keyword: "감사", theme: 3, createdAt: "05월 04일" },
  { id: "r73", to: "엄마에게", from: "딸", preview: "집에 갈게요", content: "다음 주에 집에 갈게요. 보고 싶어요.", keyword: "감사", theme: 1, createdAt: "05월 04일" },
  { id: "r74", to: "동료에게", from: "동료", preview: "수고했어요", content: "오늘 정말 고생 많았어. 내일 봅시다.", keyword: "응원", theme: 2, createdAt: "05월 04일" },
  { id: "r75", to: "친구에게", from: "친구", preview: "놀러 와", content: "이번에 자취방 이사했어. 놀러 와!", keyword: "감사", theme: 3, createdAt: "05월 04일" },
  { id: "r76", to: "연인에게", from: "연인", preview: "함께라서", content: "너랑 함께라서 요즘 너무 행복해.", keyword: "감사", theme: 1, createdAt: "05월 04일" },
  { id: "r77", to: "소중한 당신에게", from: "친구", preview: "생일인데", content: "생일인데 감사해! 선물 기대해라.", keyword: "생일", theme: 2, createdAt: "05월 04일" },
  { id: "r78", to: "선생님에게", from: "제자", preview: "가르침", content: "선생님의 가르침 잊지 않고 살겠습니다.", keyword: "감사", theme: 3, createdAt: "05월 04일" },
  { id: "r79", to: "엄마에게", from: "아들", preview: "어머니", content: "어머니, 항상 감사하고 존경합니다.", keyword: "감사", theme: 1, createdAt: "05월 04일" },
  { id: "r80", to: "친구에게", from: "친구", preview: "마지막 인사", content: "오늘 하루도 고생했고 내일도 힘내자!", keyword: "응원", theme: 2, createdAt: "05월 04일" }
];